---
driver:
  name: lxd
  ssh_key: /home/bxraabe/.ssh/braabe.telmate.com

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - 'recipe[chef-client::default]'
